const upsertFields = [
	{
		name: 'first_name',
		label: 'First name',
		placeholder: 'Enter first name',
		type: 'text',
		required: true,
	},
	{
		name: 'last_name',
		label: 'Last name',
		placeholder: 'Enter last name',
		type: 'text',
		required: true,
	},
	{
		name: 'email',
		label: 'Email',
		placeholder: 'Enter email',
		type: 'text',
		required: true,
	},
	{
		name: 'gender',
		label: 'Gender',
		placeholder: 'Select gender',
		type: 'select',
		required: true,
		data: [
			{ label: 'Male', value: 'Male' },
			{ label: 'Female', value: 'Female' },
		],
	},
	{
		name: 'country',
		label: 'Country',
		placeholder: 'Select country',
		type: 'select',
		required: true,
		data: [
			{ label: 'Vietnam', value: 'Vietnam' },
			{ label: 'Sweden', value: 'Sweden' },
			{ label: 'Argentina', value: 'Argentina' },
			{ label: 'United States', value: 'United States' },
			{ label: 'France', value: 'France' },
			{ label: 'China', value: 'China' },
			{ label: 'Indonesia', value: 'Indonesia' },
			{ label: 'Russia', value: 'Russia' },
			{ label: 'Portugal', value: 'Portugal' },
			{ label: 'Brazil', value: 'Brazil' },
			{ label: 'Czech Republic', value: 'Czech Republic' },
			{ label: 'Philippines', value: 'Philippines' },
			{ label: 'Ukraine', value: 'Ukraine' },
			{ label: 'Bulgaria', value: 'Bulgaria' },
			{ label: 'Croatia', value: 'Croatia' },
			{ label: 'Poland', value: 'Poland' },
			{ label: 'Uzbekistan', value: 'Uzbekistan' },
			{ label: 'Finland', value: 'Finland' },
			{ label: 'Ethiopia', value: 'Ethiopia' },
			{ label: 'Myanmar', value: 'Myanmar' },
			{ label: 'Bangladesh', value: 'Bangladesh' },
			{ label: 'Japan', value: 'Japan' },
			{ label: 'Colombia', value: 'Colombia' },
			{ label: 'Nigeria', value: 'Nigeria' },
			{ label: 'Pakistan', value: 'Pakistan' },
			{ label: 'Chile', value: 'Chile' },
			{ label: 'Thailand', value: 'Thailand' },
			{ label: 'Egypt', value: 'Egypt' },
			{ label: 'Italy', value: 'Italy' },
		],
	},
	{
		name: 'avatar',
		label: 'Avatar',
		placeholder: 'File',
		type: 'upload-img',
		required: true,
	},
	{
		name: 'btc_address',
		label: 'Address',
		placeholder: 'Enter address',
		type: 'text',
		required: true,
	},
]

export { upsertFields }
